'use strict';

function picture(kind, label) { return `<span class="art task-picture" role="img" aria-label="${label}">${art(kind)}</span>${label?`<b class="object-name">${label}</b>`:''}`; }

function intro(){app.innerHTML=`<section class="screen card theme-1 intro-hero"><div class="intro-copy"><div class="chapter">${t('year')}</div><h1 class="title">${t('introTitle')}</h1><p class="lead">${t('introLead')}</p><div id="introAction">${btn(S.xp?t('continue'):t('wake'),'startIntro()')}</div></div><figure class="intro-visual"><img src="assets/story/academy-arrival.png" alt="${t('introTitle')}"><div class="intro-assistant">${robot()}<div class="speech" id="speech">${t('loading')}</div></div></figure></section>`}
function startIntro(){tone(300,.1,'square');setTimeout(()=>tone(520,.15),120);el('speech').textContent=t('trainerLine');el('introAction').innerHTML=btn(t('accept'),'acceptMission()')}
function acceptMission(){if(S.xp<20)addXP(20);unlockChapter(1)}

let trainI=0;
function examplesScene(){trainI=0;resetLessonMistakes();shell(2,t('examplesTitle'),t('examplesLead'),`<div class="metrics"><div class="metric"><strong id="exCount">0 / ${objects.length}</strong>${t('examples')}</div><div class="metric"><strong id="quality">—</strong>${t('quality')}</div><div class="metric"><strong>35%</strong>${t('accuracy')}</div></div><div id="trainer"></div>`);showExample()}
function showExample(){const box=el('trainer');if(trainI>=objects.length){box.innerHTML=`${mistakeReview()}<div class="completion-panel">${robot('happy')}<div><h2>${t('datasetDone')}</h2><div class="choice">${btn(t('startTraining'),'unlockChapter(2)')}</div></div></div>`;return}const o=objects[trainI];box.innerHTML=`<div class="drag-stage"><button class="bin keep" onclick="classify('Keep',this)" ondragover="dragOver(event)" ondragleave="this.classList.remove('over')" ondrop="dropClass(event,'Keep')"><div><strong>${t('keep')}</strong><br><small>${t('useful')}</small></div></button><div class="data-card" draggable="true" ondragstart="event.dataTransfer.setData('text/plain','object')"><span class="label-chip">${t('newObject')} ${trainI+1}/${objects.length}</span>${picture(o.k,t(o.id))}<small>${t('dragHint')}</small></div><button class="bin junk" onclick="classify('Junk',this)" ondragover="dragOver(event)" ondragleave="this.classList.remove('over')" ondrop="dropClass(event,'Junk')"><div><strong>${t('junk')}</strong><br><small>${t('dangerous')}</small></div></button></div><div class="feedback">${t('remember')}</div>`}
function dragOver(e){e.preventDefault();e.currentTarget.classList.add('over')}function dropClass(e,c){e.preventDefault();e.currentTarget.classList.remove('over');classify(c,e.currentTarget)}
function classify(c,button=document.activeElement){const o=objects[trainI],ok=c===o.c,message=ok?t('correct'):registerMistake({id:o.id,kind:o.k,user:c,correct:o.c,hints:['hintObjectPurpose','hintDamageOrUseful'],explain:'explainScanner'});answerState(button,ok,message);if(ok){resolveMistake(o.id);S.quality++;addXP(18);trainI++;el('exCount').textContent=trainI+' / '+objects.length;el('quality').textContent=S.quality>7?t('excellent'):S.quality>3?t('good'):t('growing');advanceAfterFeedback(showExample)}}

function learning(){shell(3,t('learningTitle'),t('learningLead'),`<div class="learning-visual"><div class="network">${[0,1,2,3,4,5,6,7].map((_,i)=>`<i class="node" style="left:${8+(i%4)*27}%;top:${25+(i%2)*45}%;--r:${i%2?20:-20}deg;animation-delay:${i*.1}s"></i>`).join('')}</div>${robot('thinking')}</div><div class="metrics"><div class="metric"><strong id="learnAcc">35%</strong>${t('accuracy')}</div><div class="metric"><strong id="learnLev">1</strong>${t('model')}</div><div class="metric"><strong id="learnEx">0</strong>${t('scanned')}</div></div><div class="choice"><button class="cta" id="trainBtn" onclick="runTraining()">${t('start')}</button></div>`)}
function runTraining(){const button=el('trainBtn');button.disabled=true;setRobotEmotion('thinking');let i=0;const id=setInterval(()=>{i++;el('learnEx').textContent=i;const stage=Math.min(3,Math.floor(i/2));S.accuracy=CFG.accuracy[stage];el('learnAcc').textContent=S.accuracy+'%';el('learnLev').textContent=stage+1;hud();tone(300+i*45,.06);if(i===6){clearInterval(id);addXP(70);setRobotEmotion('happy');button.textContent=t('dataErrorExperiment');button.disabled=false;button.onclick=startDataErrorExperiment;toast(t('accuracy82'))}},600)}

function startDataErrorExperiment(){const examples=[['workingSat','sat','keep'],['brokenSat','broken','keep'],['debris','debris','junk']];document.querySelector('.mission-body').innerHTML=`<section class="data-experiment"><header class="experiment-heading"><span>1 / 3</span><div><h2>${t('hiddenDataErrorTitle')}</h2></div></header><div class="training-snapshot">${examples.map(([id,kind,label])=>`<article>${picture(kind,t(id))}<span>${t('label')}: <b>${t(label)}</b></span></article>`).join('')}</div><div class="choice">${btn(t('testModel'),'showBadPrediction()')}</div></section>`;showLessonBrief(t('dataBrief'))}
function showBadPrediction(){document.querySelector('.mission-body').innerHTML=`<section class="data-experiment"><header class="experiment-heading"><span>2 / 3</span><div><h2>${t('testNewExample')}</h2></div></header><div class="cause-chain"><div class="cause-card">${picture('broken',t('brokenSat'))}<span class="source-label">${t('trainingLabel')}: <b>${t('keep')}</b></span></div><i>→</i><div class="cause-card robot-result">${robot('error')}<span class="bad-decision">✕ ${t('keep')} • 84%</span></div></div><div class="data-callout error">${t('wrongDecisionShort')}</div><div class="choice">${btn(t('findCause'),'showBadDataset()')}</div></section>`}
function showBadDataset(){const examples=[['workingSat','sat','keep'],['brokenSat','broken','keep'],['debris','debris','junk']];document.querySelector('.mission-body').innerHTML=`<section class="data-experiment"><header class="experiment-heading"><span>3 / 3</span><div><h2>${t('findBadTitle')}</h2><p>${t('tapBadExample')}</p></div></header><div class="dataset-strip">${examples.map(([id,kind,label])=>`<button onclick="findBadExample('${id}',this)">${picture(kind,t(id))}<span>${t('label')}: ${t(label)}</span></button>`).join('')}</div><div class="feedback">${t('findCauseHint')}</div></section>`}
function findBadExample(id,button){if(id!=='brokenSat'){button.classList.add('shake');setTimeout(()=>button.classList.remove('shake'),400);document.querySelector('.feedback').textContent=t('badExampleHint');return}button.classList.add('found-bad');tone(650,.12);advanceAfterFeedback(showFixData,700)}
function showFixData(){document.querySelector('.mission-body').innerHTML=`<section class="data-experiment"><header class="experiment-heading"><span>3 / 3</span><div><h2>${t('fixTheLabel')}</h2><p>${t('fixDataLead')}</p></div></header><div class="label-fix-card">${picture('broken',t('brokenSat'))}<div><span class="old-label">✕ ${t('keep')}</span><i>→</i><div class="choice"><button onclick="fixBadData('keep',this)">${t('keep')}</button><button onclick="fixBadData('junk',this)">${t('junk')}</button></div></div></div><div class="feedback">${t('lookAtDamage')}</div></section>`}
function fixBadData(label,button){const ok=label==='junk';answerState(button,ok,ok?t('dataFixed'):t('lookAtDamage'));if(!ok)return;addXP(45);advanceAfterFeedback(()=>{document.querySelector('.mission-body').innerHTML=`<section class="data-result"><h2>${t('decisionChanged')}</h2><div class="model-change"><article class="before">${picture('broken',t('brokenSat'))}<small>${t('beforeFix')}</small><strong>✕ ${t('keep')} • 84%</strong></article><i>→</i><article class="after">${picture('broken',t('brokenSat'))}<small>${t('afterFix')}</small><strong>✓ ${t('junk')} • 92%</strong></article></div><div class="data-takeaway"><span>✓</span><div><b>${t('oneCardRule')}</b><small>${t('cardFixedRule')}</small></div></div><div class="choice">${btn(t('firstMission'),'unlockChapter(3)')}</div></section>`;confetti(25)},650)}

const auto=[{id:'workingSat',k:'sat',guess:'keep',correct:true,conf:86},{id:'fuelTank',k:'leakingTank',guess:'keep',correct:false,conf:62},{id:'brokenSat',k:'broken',guess:'junk',correct:true,conf:78},{id:'probe',k:'probe',guess:'junk',correct:false,conf:55}];let autoI=0;
function autonomous(){autoI=0;resetLessonMistakes();shell(4,t('autoTitle'),t('autoLead'),`<div id="auto"></div>`);showAuto()}
function showAuto(){const box=el('auto');if(autoI===auto.length){box.innerHTML=`${mistakeReview()}<div class="completion-panel">${robot('happy')}<div><h2>${t('feedbackDone')}</h2><div class="choice">${btn(t('meetUnknown'),'unlockChapter(4)')}</div></div></div>`;return}const o=auto[autoI];box.innerHTML=`<div class="decision-layout"><div class="object image-only">${picture(o.k,t(o.id))}</div><div class="robot-review">${robot(o.conf<70?'doubt':'thinking')}<div class="speech">${t('prediction')}: <b>${t(o.guess)}</b></div>${confidenceUI(o.conf)}</div></div><div class="feedback">${t('isCorrect')}</div><div class="choice"><button onclick="review(true,this)">✓ ${t('correct')}</button><button onclick="review(false,this)">✕ ${t('incorrect')}</button></div>`}
function review(v,button){const o=auto[autoI],ok=v===o.correct,message=ok?t('feedbackAdded'):registerMistake({id:o.id,kind:o.k,user:v,correct:o.correct,hints:['hintComparePrediction','hintDamageOrUseful'],explain:'explainFeedback'});answerState(button,ok,message);if(ok){resolveMistake(o.id);addXP(22);S.accuracy=Math.min(91,S.accuracy+2);autoI++;advanceAfterFeedback(showAuto)}}

let unknownI=0;
function unknowns(){unknownI=0;resetLessonMistakes();shell(5,t('unknownTitle'),t('unknownLead'),`<div id="unknown"></div>`);showUnknown()}
function showUnknown(){const box=el('unknown');if(unknownI===unfamiliar.length){box.innerHTML=`${mistakeReview()}<div class="completion-panel">${robot('happy')}<div><h2>${t('askBadge')}</h2><div class="choice">${btn(t('differentTask'),'unlockChapter(5)')}</div></div></div>`;return}const o=unfamiliar[unknownI],confidence=38+unknownI*6;box.innerHTML=`<div class="unknown-layout"><div class="unknown-task"><div class="object image-only">${picture(o.k,t(o.id))}</div>${confidenceUI(confidence)}<div class="feedback">${t('humanCheck')}</div><div class="choice"><button onclick="helpUnknown('${o.c}',this)">${t(o.c==='Keep'?'teachKeep':'teachJunk')}</button><button onclick="helpUnknown('guess',this)">${t('forceGuess')}</button></div></div><div class="unknown-robot">${robot('help')}<div class="speech">${t('notSure')}</div></div></div>`}
function helpUnknown(c,button){const o=unfamiliar[unknownI],ok=c!=='guess',message=ok?t('feedbackAdded'):registerMistake({id:o.id,kind:o.k,user:c,correct:o.c,hints:['hintSeenBefore','hintAskHuman'],explain:'explainUnknown'});answerState(button,ok,message);if(ok){resolveMistake(o.id);addXP(20);unknownI++;advanceAfterFeedback(showUnknown)}}

let orbitI=0;const paths=[
 {answer:'collision',kind:'debris',id:'debris',motion:'hit',duration:4.2},
 {answer:'safe',kind:'sat',id:'workingSat',motion:'safe',duration:4.8},
 {answer:'near',kind:'meteor',id:'meteor',motion:'near',duration:4.4}
];
function collision(){orbitI=0;resetLessonMistakes();shell(6,t('collisionTitle'),t('collisionLead'),`<div class="orbit"><div class="danger"></div><div class="mover" id="mover"></div></div><div id="pathChoice" class="choice"></div><div class="feedback" id="pathFeed">${t('observe')}</div>`);showPath()}
function showPath(){const p=paths[orbitI],moving=el('mover');el('pathChoice').innerHTML=['safe','collision','near'].map(x=>`<button onclick="pathAnswer('${x}',this)">${t(x)}</button>`).join('');moving.className='mover trajectory-'+p.motion;moving.innerHTML=art(p.kind);moving.setAttribute('aria-label',t(p.id));moving.style.animationDuration=p.duration+'s';el('pathFeed').innerHTML=`${t('observe')} ${orbitI+1} / ${paths.length}<br><b class="trajectory-label">${t(p.id)}</b>`}
function pathAnswer(x,button){const p=paths[orbitI],ok=x===p.answer,message=ok?t('correct'):registerMistake({id:p.id,kind:p.kind,user:x,correct:p.answer,hints:['hintWatchMovement','hintDangerZone'],explain:'explainCollision'});answerState(button,ok,message);if(ok){resolveMistake(p.id);addXP(25);orbitI++;advanceAfterFeedback(()=>{if(orbitI===paths.length){document.querySelector('.mission-body').innerHTML=`${mistakeReview()}<div class="completion-panel">${robot('happy')}<div><h2>${t('pathsDone')}</h2><div class="choice">${btn(t('repairLab'),'unlockChapter(6)')}</div></div></div>`}else{showPath()}})}}

let repairI=0;const repairs=[{k:'repairable',id:'repairableSat',a:'repair'},{k:'booster',id:'booster',a:'recycle'},{k:'dish',id:'comSat',a:'ignore'},{k:'leakingTank',id:'fuelTank',a:'recycle'},{k:'probe',id:'probe',a:'ignore'}];
function repair(){repairI=0;resetLessonMistakes();shell(7,t('repairTitle'),t('repairLead'),`<div id="repairGame"></div>`);showRepair()}
function showRepair(){const box=el('repairGame');if(repairI===repairs.length){box.innerHTML=`${mistakeReview()}<div class="completion-panel">${robot('happy')}<div><h2>${t('repairDone')}</h2><div class="choice">${btn(t('launch'),'unlockChapter(7)')}</div></div></div>`;return}const o=repairs[repairI];box.innerHTML=`<div class="repair-counter">${repairI+1} / ${repairs.length}</div><div class="grid"><div class="object image-only">${picture(o.k,t(o.id))}</div></div><div class="feedback">${t('repairQuestion')}</div><div class="choice">${['repair','recycle','ignore'].map(x=>`<button onclick="repairAnswer('${x}',this)">${t(x)}</button>`).join('')}</div>`}
function repairAnswer(x,button){const o=repairs[repairI],ok=x===o.a,message=ok?t('correct'):registerMistake({id:o.id,kind:o.k,user:x,correct:o.a,hints:['hintDamage','hintDamageOrUseful'],explain:'explainRepair'});answerState(button,ok,message);if(ok){resolveMistake(o.id);repairI++;addXP(24);advanceAfterFeedback(showRepair)}}

let realI=0,timer;const realTasks=[
 {type:'scanner',k:'debris',id:'debris',a:'junk',opts:['keep','junk']},
 {type:'collisionSystem',k:'meteor',id:'meteor',a:'near',opts:['safe','collision','near'],motion:'near'},
 {type:'repairSystem',k:'repairable',id:'repairableSat',a:'repair',opts:['repair','recycle','ignore']},
 {type:'scanner',k:'dish',id:'comSat',a:'keep',opts:['keep','junk']},
 {type:'scanner',k:'leakingTank',id:'fuelTank',a:'junk',opts:['keep','junk']},
 {type:'collisionSystem',k:'sat',id:'workingSat',a:'safe',opts:['safe','collision','near'],motion:'safe'},
 {type:'repairSystem',k:'booster',id:'booster',a:'recycle',opts:['repair','recycle','ignore']},
 {type:'scanner',k:'broken',id:'brokenSat',a:'junk',opts:['keep','junk']}
];
function realMission(){realI=0;S.streak=0;resetLessonMistakes();shell(8,t('realTitle'),t('realLead'),`<div class="metrics"><div class="metric"><strong id="clock">45</strong>${t('seconds')}</div><div class="metric"><strong id="combo">x1</strong>${t('combo')}</div><div class="metric"><strong id="saved">0 / 8</strong>${t('decisions')}</div></div><div id="real"></div>`);let time=45;clearInterval(timer);timer=setInterval(()=>{const clockEl=el('clock');if(!clockEl){clearInterval(timer);return}clockEl.textContent=--time;if(time<=0){clearInterval(timer);toast(t('timerExtended'))}},1000);showReal()}
function missionVisual(o){if(o.type==='collisionSystem')return `<div class="orbit mission-orbit"><div class="danger"></div><div class="mover trajectory-${o.motion}" style="animation-duration:4.4s">${art(o.k)}</div></div><div class="trajectory-legend"><span class="legend-earth"></span>${t('earthZone')}<span class="legend-danger"></span>${t('dangerZone')}</div><b class="object-name">${t(o.id)}</b>`;return `<div class="grid"><div class="object image-only">${picture(o.k,t(o.id))}</div></div>`}
function showReal(){const box=el('real');if(realI===realTasks.length){clearInterval(timer);S.accuracy=97;addXP(120);confetti();box.innerHTML=`${mistakeReview()}<div class="completion-panel">${robot('trained')}<div><h2>${t('missionDone')}</h2><div class="choice">${btn(t('emergency'),'unlockChapter(8)')}</div></div></div>`;return}const o=realTasks[realI];box.innerHTML=`<div class="chapter">${t(o.type)} • ${realI+1}/${realTasks.length}</div>${missionVisual(o)}<div class="feedback">${o.type==='collisionSystem'?t('watchFullOrbit'):t('humanCheck')}</div><div class="choice">${o.opts.map(x=>`<button onclick="realAnswer('${x}','${o.a}',this)">${t(x)}</button>`).join('')}</div>`}
function realAnswer(x,y,button){const o=realTasks[realI],ok=x===y,hints=o.type==='collisionSystem'?['hintWatchMovement','hintDangerZone']:o.type==='repairSystem'?['hintDamage','hintDamageOrUseful']:['hintObjectPurpose','hintDamageOrUseful'],explain=o.type==='collisionSystem'?'explainCollision':o.type==='repairSystem'?'explainRepair':'explainScanner',message=ok?t('correct'):registerMistake({id:o.id,kind:o.k,user:x,correct:y,hints,explain});answerState(button,ok,message);if(ok){resolveMistake(o.id);S.streak++;realI++;addXP(15+S.streak*2);el('combo').textContent='x'+(1+Math.floor(S.streak/2));el('saved').textContent=realI+' / 8';tone(520+S.streak*35,.08);advanceAfterFeedback(showReal)}else{S.streak=0;el('combo').textContent='x1'}}

function unexpected(){resetLessonMistakes();shell(9,t('unexpectedTitle'),t('unexpectedLead'),`<div class="decision-layout"><div class="object image-only">${picture('alien',t('alienObject'))}</div><div class="robot-review">${robot('help')}<div class="speech" id="alienSpeech">${t('alienLine')}</div>${confidenceUI(4)}</div></div><div class="feedback">${t('noMatch')}</div><div class="choice"><button onclick="alien('guess',this)">${t('guess')}</button><button onclick="alien('wait',this)">${t('dontKnow')}</button></div>`)}
function alien(x,button){const ok=x==='wait',message=ok?t('safeUnknown'):registerMistake({id:'alienObject',kind:'alien',user:x,correct:'wait',hints:['hintSeenBefore','hintAskHuman'],explain:'explainUnknown'});answerState(button,ok,message);if(ok){resolveMistake('alienObject');addXP(80);confetti();el('alienSpeech').textContent=t('waitScientist');advanceAfterFeedback(()=>{document.querySelector('.mission-body').innerHTML=`${mistakeReview()}<div class="completion-panel">${robot('happy')}<div><h2>${t('safeUnknown')}</h2></div></div>`;advanceAfterFeedback(()=>unlockChapter(9),2200)},900)}}

let finalTimer;
let cinematicSpeechTimer;
let cinematicSpeechRun=0;
function cinematicVoice(){const lang={ru:'ru-RU',en:'en-US',pl:'pl-PL'}[S.lang],wanted={ru:['natural','online','ирина','светлана','pavel','milena','microsoft','google'],en:['natural','online','aria','jenny','samantha','google','microsoft'],pl:['natural','online','zofia','marek','microsoft','google']}[S.lang],voices=globalThis.speechSynthesis?.getVoices?.()||[];return voices.filter(v=>v.lang.toLowerCase().startsWith(lang.slice(0,2).toLowerCase())).sort((a,b)=>wanted.reduce((score,key,i)=>score+(b.name.toLowerCase().includes(key)?wanted.length-i:0)-(a.name.toLowerCase().includes(key)?wanted.length-i:0),0))[0]||null}
function stopCinematicSpeech(){cinematicSpeechRun++;globalThis.speechSynthesis?.cancel()}
function stopFinaleRuntime(){clearInterval(finalTimer);clearTimeout(cinematicSpeechTimer);stopCinematicSpeech()}
function speakCinematic(lines,profile='story',force=false){const synth=globalThis.speechSynthesis;if(!synth||typeof SpeechSynthesisUtterance==='undefined'||(!S.sound&&!force))return;stopCinematicSpeech();const run=cinematicSpeechRun,parts=(Array.isArray(lines)?lines:[lines]).filter(Boolean),voice=cinematicVoice(),settings=profile==='action'?{rate:.92,pitch:1.03,pause:230}:profile==='finish'?{rate:.86,pitch:1.08,pause:320}:{rate:.88,pitch:1,pause:280};const next=i=>{if(run!==cinematicSpeechRun||i>=parts.length)return;const u=new SpeechSynthesisUtterance(parts[i]);u.lang={ru:'ru-RU',en:'en-US',pl:'pl-PL'}[S.lang];u.voice=voice;u.rate=settings.rate+(i===0?.02:0);u.pitch=settings.pitch;u.volume=.96;u.onend=()=>setTimeout(()=>next(i+1),settings.pause);u.onerror=()=>next(i+1);synth.speak(u)};next(0)}
function speakFinalStory(){if(!S.sound){S.sound=true;el('sound').textContent='♪';save()}speakCinematic(t('finalStoryVoice'),'story',true)}
function finale(){clearInterval(finalTimer);clearTimeout(cinematicSpeechTimer);stopCinematicSpeech();shell(10,t('finalMissionTitle'),t('finalMissionLead'),`<div class="autonomy-board awaiting-start" id="autonomyBoard"><div class="cinematic-grid"></div><div class="orbit-ring ring-one"></div><div class="orbit-ring ring-two"></div><i class="space-spark s1"></i><i class="space-spark s2"></i><i class="space-spark s3"></i><i class="space-spark s4"></i><div class="autonomy-earth"><i></i></div><div class="auto-robot">${robot('thinking')}<span class="robot-thrust"></span><span class="robot-shield"></span></div><div class="auto-object auto-meteor">${art('meteor')}</div><div class="auto-object auto-repair"><span class="repair-before">${art('repairable')}</span><span class="repair-after">${art('sat')}</span><b class="repair-label before-label">${t('beforeFix')}</b><b class="repair-label after-label">${t('afterFix')}</b></div><div class="auto-object auto-debris debris-one">${art('debris')}</div><div class="auto-object auto-debris debris-two">${art('bolt')}</div><div class="auto-object auto-debris debris-three">${art('booster')}</div><div class="auto-object auto-unknown">${art('alien')}</div><div class="scan-beam"></div><div class="avoid-route"></div><div class="repair-beam"><i></i><i></i><i></i></div><div class="orbit-collector"><span>✓</span></div><div class="human-beacon"><span>?</span><b>${t('humanCheck')}</b></div><div class="success-wave"></div><div class="mission-stamp">✓</div><div class="scene-counter"><span id="autoStep">1 / 4</span><small>SPACEAI-01 • AUTO</small></div><div class="autonomy-status"><span class="live-dot"></span><b id="autoStatus">${t('autoStarting')}</b></div><section class="cinematic-intro" id="cinematicIntro"><div class="story-signal"><span>!</span><i></i><i></i><i></i></div><div class="story-copy"><span class="story-kicker">${t('finalStoryKicker')}</span><h2>${t('finalStoryTitle')}</h2><p>${t('finalStoryText')}</p><div class="story-goals"><span>↗ ${t('finalStoryGoal1')}</span><span>✦ ${t('finalStoryGoal2')}</span><span>? ${t('finalStoryGoal3')}</span></div><div class="story-actions"><button onclick="speakFinalStory()">🔊 ${t('listen')}</button><button class="cta" onclick="startFinaleMovie(this)">${t('startFinalMovie')} →</button></div></div></section></div><div class="auto-pipeline"><div data-stage="0"><span>↗</span>${t('collisionSystem')}</div><i>→</i><div data-stage="1"><span>✦</span>${t('repairSystem')}</div><i>→</i><div data-stage="2"><span>✓</span>${t('cleanOrbit')}</div><i>→</i><div data-stage="3"><span>?</span>${t('humanCheck')}</div></div><div class="cinematic-log" id="autoLog">${t('readyForMission')}</div><div class="autonomy-result" id="autonomyResult"><strong>${t('youTrainedRobot')}</strong><span>${t('robotWorksAlone')}</span></div><div class="choice" id="finalAction"></div>`);cinematicSpeechTimer=setTimeout(()=>speakCinematic(t('finalStoryVoice')),380)}
function startFinaleMovie(button){button.disabled=true;clearTimeout(cinematicSpeechTimer);stopCinematicSpeech();const intro=el('cinematicIntro');intro.classList.add('leaving');el('autonomyBoard').classList.remove('awaiting-start');setTimeout(()=>{intro.remove();runFinale()},480)}
function runFinale(){const steps=[['autoAvoid','logAvoid'],['autoRepair','logRepair'],['autoCleanMany','logCleanMany'],['autoUnknown','logUnknown']],emotions=['doubt','thinking','happy','help'];let i=0;const advance=()=>{if(i>=steps.length){clearInterval(finalTimer);setRobotEmotion('trained');el('autoStatus').textContent=t('autoComplete');el('autoStep').textContent='✓';el('autoLog').innerHTML=`<span>✓</span>${t('autoComplete')}`;el('autonomyBoard').classList.add('stage-complete');document.querySelectorAll('.auto-pipeline div').forEach(node=>{node.classList.remove('active');node.classList.add('done')});el('autonomyResult').classList.add('visible');el('finalAction').innerHTML=`${btn(t('showCertificate'),'showCertificate()')}<button onclick="finale()">${t('replayMovie')}</button>`;speakCinematic(t('finalVoiceComplete'),'finish');confetti(70);tone(880,.35);return}setRobotEmotion(emotions[i]);el('autonomyBoard').className='autonomy-board stage-'+i;document.querySelectorAll('.auto-pipeline div').forEach((node,n)=>{node.classList.toggle('active',n===i);node.classList.toggle('done',n<i)});el('autoStep').textContent=`${i+1} / ${steps.length}`;el('autoStatus').textContent=t(steps[i][0]);el('autoLog').innerHTML=`<span>${i+1}</span>${t(steps[i][1])}`;speakCinematic(t('finalVoiceStages')[i],'action');tone(420+i*110,.18);i++};advance();finalTimer=setInterval(advance,7200)}
function showCertificate(){clearInterval(finalTimer);clearTimeout(cinematicSpeechTimer);stopCinematicSpeech();S.mode='main';save();app.innerHTML=`<section class="screen card theme-10 certificate-screen"><header class="mission-head certificate-head"><div><div class="chapter">${t('chapters')[9]}</div><h1 class="title">${t('finalTitle')}</h1><p class="lead">${t('finalLead')}</p></div><div class="graduate-badge"><span>✓</span><b>${t('mastered')}</b></div></header><div class="certificate-body"><div class="certificate-layout"><figure class="certificate-art"><img src="assets/story/orbit-success.png" alt="${t('finalTitle')}"></figure><div class="certificate"><small>SPACE AI ACADEMY</small><h2>${t('certificate')}</h2><p>${t('certifies')}</p><div class="name" contenteditable="true" id="certName" aria-label="Name">${S.name}</div><p>${t('certText')}</p><h3>${t('chief')}</h3></div></div><div class="choice certificate-actions"><button class="cta" onclick="downloadCert()">${t('download')}</button><button class="cta alt" onclick="openFreeLab()">${t('openFreeLab')}</button><button onclick="resetGame()">${t('again')}</button></div><div class="certificate-achievements">${[1,2,3,4].map(i=>`<div><span>✓</span><small>${t('lesson'+i)}</small></div>`).join('')}</div></div></section>`;confetti(90)}
function downloadCert(){S.name=el('certName').textContent.trim()||t('chief');save();const c=document.createElement('canvas');c.width=1400;c.height=900;const x=c.getContext('2d');x.fillStyle='#f7f1d5';x.fillRect(0,0,1400,900);x.strokeStyle='#c89d25';x.lineWidth=18;x.strokeRect(30,30,1340,840);x.strokeStyle='#17254a';x.lineWidth=4;x.strokeRect(55,55,1290,790);x.textAlign='center';x.fillStyle='#16244a';x.font='bold 34px Arial';x.fillText('SPACE AI ACADEMY',700,145);x.font='bold 66px Georgia';x.fillText(t('certificate'),700,265);x.font='30px Arial';x.fillText(t('certifies'),700,350);x.font='italic 60px Georgia';x.fillText(S.name,700,445);x.beginPath();x.moveTo(330,470);x.lineTo(1070,470);x.stroke();x.font='25px Arial';x.fillText(t('certText'),700,545);x.font='bold 40px Arial';x.fillText(t('chief'),700,655);const a=document.createElement('a');a.download='space-ai-academy-certificate.png';a.href=c.toDataURL('image/png');a.click();tone(880,.35)}
function resetGame(){localStorage.removeItem('spaceAI');location.reload()}
function render(){hud();syncChrome();if(S.mode==='free'){freeLab();return}[intro,examplesScene,learning,autonomous,unknowns,collision,repair,realMission,unexpected,finale][S.chapter]()}
el('sound').onclick=()=>{S.sound=!S.sound;el('sound').textContent=S.sound?'♪':'×';save();tone(500)};el('sound').textContent=S.sound?'♪':'×';render();
